name: PHPUnit tests
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'

    name: using PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php-versions }}-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run unit tests
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text
